#!/bin/sh

npm run build
cp -r build/* slideCreator/static/
rm -r slideCreator/static/js slideCreator/static/css
mv slideCreator/static/index.html slideCreator/templates/index.html
mv slideCreator/static/static/* slideCreator/static/
rm -r build
rmdir slideCreator/static/static
